"""Added permissions and expanded teams

Revision ID: 1305fa464ea1
Revises: 58e76b3908b2
Create Date: 2023-08-13 10:56:02.072217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1305fa464ea1'
down_revision: Union[str, None] = '58e76b3908b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
